Experimental changes
See "changelog.md" for full details.

diff --git a/utils/preupgrade b/utils/preupgrade
--- a/utils/preupgrade
+++ b/utils/preupgrade
@@ -1,3 +1,9 @@
+# Upgrading from original MassOS (pre-2023) is not allowed.
+if [ "$(cat /etc/massos-release | cut -d'-' -f1)" != "experimental" ]; then
+  echo "Error: Upgrading from a pre-2023 MassOS version is not allowed." >&2
+  echo "Please back up your personal data and perform a clean reinstall." >&2
+  exit 1
+fi
 # Check for a new version of Glibc (breaks this utility).
 if [ "$(ldd --version | head -n1 | cut -d' ' -f4)" != "2.36" ]; then
   echo "
@@ -7,7 +13,7 @@ therefore not possible. To upgrade, please boot a MassOS live environment, run
 the installation program, and choose 'Repair' --> 'Refresh'. This won't erase
 your apps or data. For information on how to do this, see the following URL:
 
-  https://github.com/MassOS-Linux/MassOS/blob/main/installation-guide.md
+  https://github.com/MassOS-Linux/MassOS/wiki/Upgrading-MassOS
 " >&2
   exit 1
 fi
diff --git a/utils/programs/adduser b/utils/programs/adduser
--- a/utils/programs/adduser
+++ b/utils/programs/adduser
@@ -1,92 +1,107 @@
-#!/bin/bash
+#!/usr/bin/env bash
 # User creation utility for MassOS.
-# Copyright (C) 2021-2022 MassOS Developers.
+# Copyright (C) 2021-2024 Daniel Massey / MassOS Developers.
 
-if [ $EUID -ne 0 ]; then
-  echo "Error: adduser must be run as root." >&2
+if test $EUID -ne 0; then
+  echo "Error: $(basename "$0") must be run as root." >&2
   exit 1
 fi
 
-if [ ! -z "$1" ]; then
-  username1="$1"
+# Check if the username was supplied as an argument.
+if test ! -z "$1"; then
+  username_input="$1"
 fi
 
-read -p "Enter the full name of the new user: " fullname
+# Ask the user for the full name.
+read -rp "Enter the full name of the new user: " fullname
 
-while [ -z "$username1" ]; do
-  read -p "Enter the username of the new user: " username1
-  if [ -z "$fullname" -a -z "$username1" ]; then
+# Enter a loop until an acceptable username is given or determinable by us.
+while test -z "$username_input"; do
+  # Ask the user for the username because it wasn't given as an argument.
+  read -rp "Enter the username of the new user: " username_input
+  if test -z "$fullname" && test -z "$username_input"; then
+    # Full name can be empty, but username must not be.
     echo "Username must not be empty."
-  elif [ -z "$username1" ]; then
-    username1="$fullname"
+  elif test -z "$username_input"; then
+    # Username is empty, so set it to the full name was.
+    username_input="$fullname"
   fi
 done
-username2=$(echo "$username1"  | head -n1 | cut -d " " -f1)
-username=$(echo $username2 | tr '[:upper:]' '[:lower:]')
 
-if [ -z "$fullname" ]; then
+# Filter the username so it is a single word and converted to lowercase.
+username="$(echo "$username_input" | head -n1 | cut -d' ' -f1 | tr '[:upper:]' '[:lower:]')"
+
+# If the full name was not specified, it will be set to the username.
+if test -z "$fullname"; then
   fullname="$username"
 fi
 
-read -p "Default login shell (/bin/bash): " shell
-if [ -z "$shell" ]; then
-  shell=/bin/bash
-elif [ ! -x "$shell" ]; then
-  echo "Warning: $shell is not a valid shell. Falling back to '/bin/bash'." >&2
+# Ask the user for their preferred login shell.
+read -rp "Login shell (leave blank for default (/bin/bash)): " shell
+
+# Fallback to bash is the user did not specify a shell.
+if test -z "$shell"; then
   shell=/bin/bash
 fi
 
-echo "Admin privileges adds the user to groups wheel, netdev and lpadmin."
-read -p "Enable admin privileges for the user? [Y/n] " adminsel1
-adminsel=$(echo "$adminsel1" | tr '[:upper:]' '[:lower:]')
-if [ "$adminsel" = n ] || [ "$adminsel" = no ]; then
-  admin=n
+# Emit a warning if the specified shell is not valid, and fallback to bash.
+if test ! -x "$shell"; then
+  echo "WARNING: $shell is not a valid shell. Falling back to '/bin/bash'." >&2
+  shell=/bin/bash
+fi
+
+# Tell the user about admin and ask them if they want the user to be an admin.
+echo "Admin users are part of the 'wheel' group and can elevate to 'root'."
+read -rp "Should $username be an admin user on the system? [Y/n] " adminsel_input
+
+# Convert the input to lowercase.
+adminsel=$(echo "$adminsel_input" | tr '[:upper:]' '[:lower:]')
+
+# Assume YES unless the user specified otherwise.
+if test "$adminsel" = n || test "$adminsel" = no; then
+  admin="NO"
 else
-  admin=y
+  admin="YES"
 fi
 
-if [ $admin = y ]; then
-  groups="wheel,netdev,lpadmin"
-fi
-
-read -p "Enter a comma-separated list of any extra groups for the user: " g
-if [ ! -z "$g" ]; then
-  groups="$groups,$g"
-fi
-
+# Final warning.
 echo "Your user will be configured with the following settings:
 
 Full name: $fullname
 Username: $username
 Login shell: $shell
-Groups: $groups
+Admin: $admin
 "
-read -p "Press Enter to continue or CTRL+C to abort: "
+read -rp "Press Enter to continue or CTRL+C to abort: "
 
-if [ -z "$groups" ]; then
-  useradd -mc "$fullname" -s "$shell" $username
-  if [ $? -ne 0 ]; then
+if test "$admin" = "NO"; then
+  # Create the user without any additional groups.
+  useradd -c "$fullname" -ms "$shell" "$username"
+  if test $? -ne 0; then
+    # Something went very wrong.
     echo "Error creating user. Exiting..." >&2
     exit 1
   fi
 else
-  useradd -mc "$fullname" -G "$groups" -s "$shell" $username
-  if [ $? -ne 0 ]; then
+  # Create the user with the relevant group(s) for admin.
+  useradd -c "$fullname" -G wheel -ms "$shell" "$username"
+  if test $? -ne 0; then
+    # Something went very wrong.
     echo "Error creating user. Exiting..." >&2
     exit 1
   fi
 fi
 
-return=1
-while [ $return = 1 ]; do
-  passwd $username
-  if [ $? -ne 0 ]; then
-    return=1
-  else
-    return=0
-  fi
+# Enter a loop for setting the password, so we can retry if it fails.
+while true; do
+  passwd "$username"
+  test $? -eq 0 || continue
+  break
 done
 
-chmod 700 /home/$username
+# Ensure only the user has access to their home directory.
+chmod 0700 /home/"$username"
 
+# Finishing message.
 echo "User $username created successfully."
+echo "To add $username to extra groups, run 'usermod -aG <group> $username'."
